Added update script and updated README
rapidsai/notebooks pull request #332
Opened 2020-10-22 21:56 UTC by msadang

2020-10-22 22:02 UTC, ajschmidt8 approved these changes
looks good. one minor suggestion to use backticks around `./update.sh`.

2020-10-22 22:02 UTC, ajschmidt8 commented on README.md
> +To get the latest notebook repo updates, run the update.sh script or use the following command:
```suggestion
To get the latest notebook repo updates, run `./update.sh` or use the following command:
```

2020-10-22 22:03 UTC, mike-wendt requested changes

2020-10-22 22:03 UTC, mike-wendt commented on update.sh
> +git submodule update --init --remote --no-single-branch --depth 1
I would add `#!/bin/bash` at the start to be safe

Also add `git pull` before the submodule call so we have the latest content from the repo if this has been checked out previously

2020-10-22 22:03 UTC, mike-wendt commented on README.md
> +To get the latest notebook repo updates, run the update.sh script or use the following command:
I would add ticks around `update.sh` so it's easier to ready

2020-10-23 00:59 UTC, harrism requested changes
This doesn't really solve the problem we're having with this repo. THe problem is that the RAPIDS team is not updating the submodule links to the correct version at every release.  It would be great if we could automate that or make it part of the release process (ideally when notebooks `branch-0.18` is created, the links should automatically be updated to point at the corresponding branches of the submodules, if submodules are allowed to point at branches and not commits).

2020-10-23 00:59 UTC, harrism commented on update.sh
> +git submoidule update --init --remote --no-single-branch --depth 1
```suggestion
git submodule update --init --remote --no-single-branch --depth 1
```

2020-10-23 05:12 UTC, msadang commented
rerun test

2020-10-23 20:23 UTC, mike-wendt commented
> This doesn't really solve the problem we're having with this repo. THe problem is that the RAPIDS team is not updating the submodule links to the correct version at every release. It would be great if we could automate that or make it part of the release process (ideally when notebooks `branch-0.18` is created, the links should automatically be updated to point at the corresponding branches of the submodules, if submodules are allowed to point at branches and not commits).

@harrism we already use [branches](https://github.com/rapidsai/notebooks/blob/branch-0.17/.gitmodules) for the submodules. The commits in this repo are the latest that were available when we made the update.

This is why we run 
```
git submodule update --init --remote --no-single-branch --depth 1
```
as that walks to the tip of the branches in all of the repos and provides the update without us having to constantly commit to this repo every night.

The `update.sh` script is just a way for people like DSWS and others to stay on `main` branch and then run `./update.sh` to get the next release and the latest notebooks.

2020-10-23 20:34 UTC, mike-wendt approved these changes

2020-10-24 00:58 UTC, merged